name: ci

on:
  schedule:
    # build every first of the month
    - cron: '0 0 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - node: 12
            tags: "pluswerk/node-dev:12"
          - node: 13
            tags: "pluswerk/node-dev:13"
          - node: 14
            tags: "pluswerk/node-dev:14"
          - node: 15
            tags: "pluswerk/node-dev:15"
          - node: 16
            tags: "pluswerk/node-dev:16"
          - node: 17
            tags: "pluswerk/node-dev:17"
          - node: 18
            tags: "pluswerk/node-dev:lts,pluswerk/node-dev:18"
          - node: 19
            tags: "pluswerk/node-dev,pluswerk/node-dev:current,pluswerk/node-dev:19"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.node }}
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          registry: ghcr.io
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ matrix.tags }}
          build-args: FROM=node:${{ matrix.node }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_dev.outputs.digest }}
